'use strict'

const Telegram = require('telegram-node-bot');
const tg = new Telegram.Telegram('369024334:AAGhqF6k9ItpVdunL5HnJzkc6p5rBx_sFB0');

const kompaktbaggerController = require('./controllers/Baumaschienen');
const startController = require('./controllers/start')
const verdichtungsController = require('./controllers/verdichtungstechnik')
const anhaengerController = require('./controllers/Anhänger')

tg.router
.when(new Telegram.TextCommand('/start', 'startCommand'),new startController())
.when(new Telegram.TextCommand('/hi', 'startCommand'),new startController())
.when(new Telegram.TextCommand('/hallo', 'startCommand'),new startController())
.when(new Telegram.TextCommand('/Hi', 'startCommand'),new startController())
.when(new Telegram.TextCommand('/Hallo', 'startCommand'),new startController())
tg.router
.when(new Telegram.TextCommand('/Anhaenger', 'anhaengerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/Humbaur_Tieflader', 'Humbaur_TiefladerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/DetailsHumbaur_Tieflader', 'detailsHumbaur_TiefladerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/ReservierenHumbaur_Tieflader', 'reservierenHumbaur_TiefladerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/Humbaur_Planenanhaenger', 'Humbaur_PlanenanhaengerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/DetailsHumbaur_Planenanhaenger', 'detailsHumbaur_PlanenanhaengerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/ReservierenHumbaur_Planenanhaenger', 'reservierenHumbaur_PlanenanhaengerCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/Boeckmann_Kipper', 'Boeckmann_KipperCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/DetailsBoeckmann_Kipper', 'detailsBckoemann_KipperCommand'),new anhaengerController())
.when(new Telegram.TextCommand('/ReservierenBoeckmann_Kipper', 'reservierenBoeckmann_KipperCommand'),new anhaengerController())
tg.router
.when(new Telegram.TextCommand('/Verdichtunstechnik', 'verdichtunsCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/Stampfer', 'stampferCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/Vibrationsplatte', 'vibrationsplatteCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BT60', 'BOMAG_BT60Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BT60', 'detailsBOMAG_BT60Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BT60', 'reservierenBOMAG_BT60Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BT65', 'BOMAG_BT65Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BT65', 'detailsBOMAG_BT65Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BT65', 'reservierenBOMAG_BT65Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BP1035', 'BOMAG_BP1035Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BP1035', 'detailsBOMAG_BP1035Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BP1035', 'reservierenBOMAG_BP1035Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BP2050', 'BOMAG_BP2050Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BP2050', 'detailsBOMAG_BP2050Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BP2050', 'reservierenBOMAG_BP2050Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BPR2540', 'BOMAG_BPR2540Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BPR2540', 'detailsBOMAG_BPR2540Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BPR2540', 'reservierenBOMAG_BPR2540Command'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BPR3560D', 'BOMAG_BPR3560DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BPR3560D', 'detailsBOMAG_BPR3560DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BPR3560D', 'reservierenBOMAG_BPR3560DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BPR6065D', 'BOMAG_BPR6065DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BPR6065D', 'detailsBOMAG_BPR6065DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BPR6065D', 'reservierenBOMAG_BPR6065DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/BOMAG_BPR7070D', 'BOMAG_BPR7070DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/DetailsBOMAG_BPR7070D', 'detailsBOMAG_BPR7070DCommand'),new verdichtungsController())
.when(new Telegram.TextCommand('/ReservierenBOMAG_BPR7070D', 'reservierenBOMAG_BPR7070DCommand'),new verdichtungsController())
tg.router
    .when(new Telegram.TextCommand('/Baumaschienen', 'bauCommand'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/Kompaktbagger', 'kompaktbaggerCommand'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaU10', 'kubotaU10Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaU10', 'detailsKubotaU10Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaU10', 'reservierenKubotaU10Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/Takeuchi_Tb_216', 'Takeuchitb216Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsTakeuchi_Tb_216', 'detailsTakeuchitb216Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenTakeuchi_Tb_216', 'reservierenTakeuchitb216Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaKX61_3', 'KubotaKX613Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaKX61_3', 'detailsKubotaKX613Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaKX61_3', 'reservierenKubotaKX613Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaKX71_3', 'KubotaKX713Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaKX71_3', 'detailsKubotaKX713Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaKX71_3', 'reservierenKubotaKX713Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaKX101_3', 'KubotaKX1013Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaKX101_3', 'detailsKubotaKX1013Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaKX101_3', 'reservierenKubotaKX1013Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaKX121_3a', 'KubotaKX1213aCommand'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaKX121_3a', 'detailsKubotaKX1213aCommand'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaKX121_3a', 'reservierenKubotaKX1213aCommand'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KubotaU55', 'KubotaU55Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKubotaU55', 'detailsKubotaU55Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKubotaU55', 'reservierenKubotaU55Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/KomatsuPC138', 'KomatsuPC138Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/DetailsKomatsuPC138', 'detailsKomatsuPC138Command'),new kompaktbaggerController())
    .when(new Telegram.TextCommand('/ReservierenKomatsuPC138', 'reservierenKomatsuPC138Command'),new kompaktbaggerController())
